(load "./rational.lsp")

(setq n 12000)
(setq a 0 b 1 c 1 d n)
;(println a "/" b)
(setq left '(1 3))
(setq right '(1 2))
(setq result 0)
(while (<= c n)
        (setq k (/ (+ n b) d))
        (setq _c c)
        (setq _d d)
        (setq c (- (* k c) a))
        (setq d (- (* k d) b))
        (setq a _c)
        (setq b _d)
        (and 
            (Q:< left  (list a b))
            (Q:> right (list a b))
            (inc result)
        )
        ;(println a "/" b)
)
(println result)
(exit)

